config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    resources :brands, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :product_types, only: [:index, :new, :create]
    resources :users, only: [:index]
    resources :conversations, only: [:index, :new, :show]
    resources :personal_messages, only: [:new, :create]
    resources :orders, only: [] do
      collection do
        get :unpaid_orders
        get :paid_orders
        get :shipped_orders
      end
      member do
        get :ship_order
      end
    end
  end
  resources :shopping_carts, except: [:new, :create, :edit, :update, :destroy, :index, :show] do
    collection do
      get 'checkout'
      post 'process_payment'
      get 'remove_items_from_cart'
    end
  end
  resources :conversations
  resources :personal_messages

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", passwords: 'users/passwords' }
  root to: 'home#index'
  get 'home/shop' => "home#shop", as: :shop
  get 'home/sub_categories' => "home#sub_categories", as: :sub_categories
  get 'home/product_types' => "home#product_types", as: :product_types
  get 'home/product' => "home#product", as: :product
  get 'home/cart' => "home#cart", as: :cart
  get 'home/contact' => "home#contact", as: :contact
  get 'home/blog' => "home#blog", as: :blog
  get 'home/blog_show' => "home#blog_show", as: :blog_show
  get 'home/add_favorite' => "home#add_favorite", as: :add_favorite
  get 'home/remove_favorite' => "home#remove_favorite", as: :remove_favorite
  get 'home/my_favorites' => "home#my_favorites", as: :my_favorites
  get 'home/add_to_cart' => "home#add_to_cart", as: :add_to_cart
  post 'home/create_shipping' => "home#create_shipping", as: :create_shipping
  get 'home/product_detail_modal' => "home#product_detail_modal", as: :product_detail_modal
  get 'home/about_us' => "home#about_us", as: :about_us
  get 'home/contact_us' => "home#contact_us", as: :contact_us
  get 'home/terms_of_use' => "home#terms_of_use", as: :terms_of_use
  get 'home/discount_policy' => "home#discount_policy", as: :discount_policy
  get 'home/return' => "home#return", as: :return
  get 'home/privacy_policy' => "home#privacy_policy", as: :privacy_policy
  get 'home/shipping_help' => "home#shipping_help", as: :shipping_help
  get 'home/see_all' => 'home#see_all'
  resources :dashboards do
    collection do
      get :order_shipping_details
    end
  end

  get 'catergory_list' => "dashboards#catergory_list", as: :catergory_list
  get 'add_catergory' => "dashboards#add_catergory", as: :add_catergory
  post 'create_catergory' => "dashboards#create_catergory", as: :create_catergory
  get 'edit_category' => "dashboards#edit_category", as: :edit_category
  put 'update_category' => "dashboards#update_category", as: :update_category

  get 'sub_category_list' => "dashboards#sub_category_list", as: :sub_category_list
  get 'add_sub_category' => "dashboards#add_sub_category", as: :add_sub_category
  post 'create_sub_category' => "dashboards#create_sub_category", as: :create_sub_category

  get 'store' => "dashboards#store", as: :store
  get 'add_store' => "dashboards#add_store", as: :add_store
  post 'create_store' => "dashboards#create_store", as: :create_store

  get 'product_list' => "dashboards#product_list", as: :product_list
  get 'add_product' => "dashboards#add_product", as: :add_product
  post 'create_product' => "dashboards#create_product", as: :create_product
  get 'edit_product' => "dashboards#edit_product", as: :edit_product
  put 'update_product' => "dashboards#update_product", as: :update_product
  get 'delete_product' => "dashboards#delete_product", as: :delete_product

  get 'product_color_list' => "dashboards#product_color_list", as: :product_color_list
  get 'add_product_color' => "dashboards#add_product_color", as: :add_product_color
  post 'create_product_color' => "dashboards#create_product_color", as: :create_product_color

  get 'product_size_list' => "dashboards#product_size_list", as: :product_size_list
  get 'add_product_size' => "dashboards#add_product_size", as: :add_product_size
  post 'create_product_size' => "dashboards#create_product_size", as: :create_product_size

  get 'closure_type_list' => "dashboards#closure_type_list", as: :closure_type_list
  get 'add_closure_type' => "dashboards#add_closure_type", as: :add_closure_type
  post 'create_closure_type' => "dashboards#create_closure_type", as: :create_closure_type


  get 'collar_list' => "dashboards#collar_list", as: :collar_list
  get 'add_collar_type' => "dashboards#add_collar_type", as: :add_collar_type
  post 'create_collar_type' => "dashboards#create_collar_type", as: :create_collar_type

  get 'craft_list' => "dashboards#craft_list", as: :craft_list
  get 'add_craft_type' => "dashboards#add_craft_type", as: :add_craft_type
  post 'create_craft_type' => "dashboards#create_craft_type", as: :create_craft_type


  get 'design_list' => "dashboards#design_list", as: :design_list
  get 'add_design' => "dashboards#add_design", as: :add_design
  post 'create_design' => "dashboards#create_design", as: :create_design

  get 'design_type_list' => "dashboards#design_type_list", as: :design_type_list
  get 'add_design_type' => "dashboards#add_design_type", as: :add_design_type
  post 'create_design_type' => "dashboards#create_design_type", as: :create_design_type

  get 'pattern_style_list' => "dashboards#pattern_style_list", as: :pattern_style_list
  get 'add_pattern_style' => "dashboards#add_pattern_style", as: :add_pattern_style
  post 'create_pattern_style' => "dashboards#create_pattern_style", as: :create_pattern_style


  get 'sleeve_type_list' => "dashboards#sleeve_type_list", as: :sleeve_type_list
  get 'add_sleeve_type' => "dashboards#add_sleeve_type", as: :add_sleeve_type
  post 'create_sleeve_type' => "dashboards#create_sleeve_type", as: :create_sleeve_type


  get 'styles_list' => "dashboards#styles_list", as: :styles_list
  get 'add_style' => "dashboards#add_style", as: :add_style
  post 'create_style' => "dashboards#create_style", as: :create_style

  get 'shipping_prices' => "dashboards#shipping_prices", as: :shipping_prices
  get 'add_shipping_prices' => "dashboards#add_shipping_prices", as: :add_shipping_prices
  post 'create_shipping_price' => "dashboards#create_shipping_price", as: :create_shipping_price

  get 'orders_list' => "dashboards#orders_list", as: :orders_list
  get 'pending_orders' => "dashboards#pending_orders", as: :pending_orders
  get 'completed_orders' => "dashboards#completed_orders", as: :completed_orders
  get 'order_details' => "dashboards#order_details", as: :order_details
  get 'my_order_details' => "dashboards#my_order_details", as: :my_order_details
  get 'change_product_status' => "dashboards#change_product_status", as: :change_product_status
  get 'change_order_status' => "dashboards#change_order_status", as: :change_order_status
  mount ActionCable.server => '/cable'

  #For static pages
  get "/pages/:page" => "pages#show"
  resources :states, only: :index
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  def checkout
    # byebug
    if params[:value].present?
      @value = params[:value]
    end
    if current_user.present? && current_user.orders.present?
      @order_items = current_user.orders.pending
      if @order_items.present?
        @order_items = current_user.orders.pending.last.order_items
      end
    end
    if current_user.present?
      if current_user.shipping.present?
        @shipping = current_user.shipping
      else
        @shipping = Shipping.new
      end
      render layout: "purchase_application"
    else
      redirect_to user_session_path
    end
  end

  def process_payment
    @order = current_user.orders.last
    location = SquareConnectServices.location(flash)
    begin
      responce = SquareConnectServices.transaction(params[:nonce], @order.total_price.to_i)
      flash[:notice] = "Card Charged successfully"
      session.delete(:shop_cart)
      @order.update(status:"paid")
      url = "#{request.base_url}/my_order_details?id=#{@order.id}"
      MessageMailer.email_admin(current_user, url, @order).deliver_now
      MessageMailer.order_email(current_user.email, current_user.name, current_user, url, @order).deliver_now
      redirect_to  checkout_shopping_carts_path(value: "done")
    rescue SquareConnect::ApiError => e
      flash[:notice] = "Error encountered while charging card: #{e.message}"
      redirect_to checkout_shopping_carts_path and return
    end
  end

  def remove_items_from_cart
    session[:shop_cart].present? ? session[:shop_cart].each {|product| session[:shop_cart].delete(product) if product == params[:product]} : OrderItem.find(params[:order_item].to_i).destroy
    redirect_to checkout_shopping_carts_path
  end

  private
    def card_params
      params.require(:card_info).permit(:first_name, :last_name, :card_type, :card_expires_on, :card_verification, :card_number)
    end
end

app/views/shopping_carts/_checkout_order_states.html.erb
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <div class="purchase-main">
      <ol class="progress-bar">
        <% if @value == "review_order" %>
          <li class="progress-bar__steps current">
            <span class="progress-bar__steps--text ">Review your Order</span>
          </li>
          <li class="progress-bar__steps">
            <span class="progress-bar__steps--text">Payment</span>
          </li>
          <li class="progress-bar__steps">
            <span class="progress-bar__steps--text">Done</span>
          </li>
        <% elsif @value == "payment" %>
          <li class="progress-bar__steps">
            <span class="progress-bar__steps--text ">Review your Order</span>
          </li>
          <li class="progress-bar__steps current">
            <span class="progress-bar__steps--text">Payment</span>
          </li>
          <li class="progress-bar__steps">
            <span class="progress-bar__steps--text">Done</span>
          </li>
        <% elsif @value == "done" %>
          <li class="progress-bar__steps">
            <span class="progress-bar__steps--text ">Review your Order</span>
          </li>
          <li class="progress-bar__steps">
            <span class="progress-bar__steps--text">Payment</span>
          </li>
          <li class="progress-bar__steps current">
            <span class="progress-bar__steps--text">Done</span>
          </li>
        <% end %>
      </ol>
    </div>
    <b> 1. Select your shipping information: </b>
  </div>
</div>

app/views/shopping_carts/_order_address.html.erb
<div class="row" id="address-group-penal">
  <div class="col-lg-10 offset-lg-1">
    <div class="adress-panel">
      <div class="default">
        <p>Default address</p>
      </div>
      <div class="panel-body">
        <div class="row">
          <input type="radio" checked>
          <label><%= current_user.shipping.name if current_user.shipping.present? %></label>
        </div>
        <div class="row">
          <div class="caption">
            <img src="/assets/contact_3.png" alt="">
            <p><%= "#{current_user.shipping.street_address_one}, #{current_user.shipping.street_address_two}" if current_user.shipping.present? %></p>
            <p><%= "#{current_user.shipping.city}, #{current_user.shipping.state}, #{current_user.shipping.postal_code}"if current_user.shipping.present? %>
            </p>
            <p><%= current_user.shipping.cntry_name if current_user.shipping.present? %></p>
          </div>
        </div>
        <div class="row">
          <div class="caption">
            <img src="/assets/phone.png" alt="">
            <p><%= current_user.shipping.mobile if current_user.shipping.present? %></p>
          </div>
        </div>
      </div>
      <div class="edit">
        <a href="#" class="show-inputs-group">
          <span class="glyphicon glyphicon-pencil"></span>
          Edit
        </a>
      </div>
    </div>
    <a href="#" class="show-inputs-group">
      <span class="glyphicon glyphicon-plus"></span>
      Add a new address
    </a>
  </div>
</div>

app/views/shopping_carts/_order_payment.html.erb
<div class = "hahah">
</div>
<b> 3. Payment method </b>
<div class="card" style="width: 50rem;">
  <div class = "card-body" >
    <div id="payment-panel">
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <div class="sq-payment-form">
  <div id="sq-walletbox">
    <button id="sq-google-pay" class="button-google-pay"></button>
    <button id="sq-apple-pay" class="sq-apple-pay"></button>
    <button id="sq-masterpass" class="sq-masterpass"></button>
    <div class="sq-wallet-divider">
      <span class="sq-wallet-divider__text">Or</span>
    </div>
  </div>
  <div id="sq-ccbox">
    <form id="nonce-form" novalidate action="/shopping_carts/process_payment" method="post">
      <div class="sq-field">
        <label class="sq-label">Card Number</label>
        <div id="sq-card-number"></div>
      </div>
      <div class="sq-field-wrapper">
        <div class="sq-field sq-field--in-wrapper">
          <label class="sq-label">CVV</label>
          <div id="sq-cvv"></div>
        </div>
        <div class="sq-field sq-field--in-wrapper">
          <label class="sq-label">Expiration</label>
          <div id="sq-expiration-date"></div>
        </div>
        <div class="sq-field sq-field--in-wrapper">
          <label class="sq-label">Postal</label>
          <div id="sq-postal-code"></div>
        </div>
      </div>
      <div class="sq-field">
        <button id="sq-creditcard" class="sq-button" onclick="onGetCardNonce(event)">
          Pay <%= number_to_currency(cart_total) %> Now
        </button>
      </div>
      <!--
        After a nonce is generated it will be assigned to this hidden input field.
      -->
      <div id="error"></div>
      <input type="hidden" id="card-nonce" name="nonce">
    </form>
  </div>
</div>
          </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <div class="cart_buttons">
      <%= link_to "Continue Shopping", root_path, class: "button cart_button_checkout" %>
    </div>
  </div>
</div>

<!-- End Payment Form -->

app/views/shopping_carts/_review_order.html.erb
<div class="cart_items">
  <div class="checkout_review_items"> 2. Review and confirm your order (<%= @order_items.size if @order_item.present? %>): </div>
  <ul class="cart_list mb-5">
    <% if !session[:shop_cart].nil? && session[:shop_cart].count > 0 %>
      <% session[:shop_cart].each do |product| %>
        <li class="cart_item clearfix">
          <div class="cart_item_image"><img src="<%= product_details(product[0].to_i).product_images.first.image.url(:thumb) if product_details(product[0].to_i).product_images.present? %>" alt=""></div>
          <div class="cart_item_info d-flex flex-md-row flex-column justify-content-between">
            <div class="cart_item_name cart_info_col">
              <div class="cart_item_title">Remove Item</div>
              <div class="cart_item_text"> <%= link_to "Remove Item", remove_items_from_cart_shopping_carts_path(product: product) %></div>
            </div>
            <div class="cart_item_name cart_info_col">
              <div class="cart_item_title">Name</div>
              <div class="cart_item_text"><%= product_details(product[0].to_i).name.truncate(18) %></div>
            </div>
            <div class="cart_item_color cart_info_col">
              <div class="cart_item_title">Color</div>
              <div class="cart_item_text"><%= product[3] %></div>
            </div>
            <div class="cart_item_quantity cart_info_col">
              <div class="cart_item_title">Quantity</div>
              <div class="cart_item_text"><%= product[1] %></div>
            </div>
            <div class="cart_item_quantity cart_info_col">
              <div class="cart_item_title">Shipping Fee</div>
              <div class="cart_item_text"><%= number_to_currency(product[4].to_i*product[1].to_i) %></div>
            </div>
            <div class="cart_item_price cart_info_col">
              <div class="cart_item_title">Price</div>
              <div class="cart_item_text"><%= number_to_currency(product_details(product[0].to_i).price*product[1].to_i) %></div>
            </div>
            <div class="cart_item_total cart_info_col">
              <div class="cart_item_title">Total</div>
              <div class="cart_item_text"><%= number_to_currency(product_details(product[0].to_i).price*product[1].to_i+product[4].to_i*product[1].to_i) %></div>
            </div>
          </div>
        </li>
      <% end %>
    <% else %>
      <% if @order_items.present? %>
        <% @order_items.each do |order_item| %>
          <li class="cart_item clearfix">
            <div class="cart_item_image"><img src="<%= product_details(order_item.product_id).product_images.first.image.url(:thumb) if product_details(order_item.product_id).product_images.present? %>" alt=""></div>
            <div class="cart_item_info d-flex flex-md-row flex-column justify-content-between">
              <div class="cart_item_name cart_info_col">
                <div class="cart_item_title">Remove Item</div>
                <div class="cart_item_text"> <%= link_to "Remove Item", remove_items_from_cart_shopping_carts_path(order_item: order_item) %></div>
              </div>
              <div class="cart_item_name cart_info_col">
                <div class="cart_item_title">Name</div>
                <div class="cart_item_text"><%= product_details(order_item.product_id).name.truncate(18) %></div>
              </div>
              <div class="cart_item_color cart_info_col">
                <div class="cart_item_title">Color</div>
                <div class="cart_item_text"><%= order_item.color %></div>
              </div>
              <div class="cart_item_quantity cart_info_col">
                <div class="cart_item_title">Quantity</div>
                <div class="cart_item_text"><%= order_item.quantity %></div>
              </div>

              <div class="cart_item_quantity cart_info_col">
                <div class="cart_item_title">Shipping Fee</div>
                <div class="cart_item_text"><%= number_to_currency(order_item.shipping.to_i*order_item.quantity) %></div>
              </div>
              <div class="cart_item_price cart_info_col">
                <div class="cart_item_title">Price</div>
                <div class="cart_item_text"><%= number_to_currency(product_details(order_item.product_id).price*order_item.quantity.to_i) %></div>
              </div>
              <div class="cart_item_total cart_info_col">
                <div class="cart_item_title">Total</div>
                <div class="cart_item_text"><%= number_to_currency((product_details(order_item.product_id).price+order_item.shipping.to_i)*order_item.quantity) %></div>
              </div>
            </div>
          </li>
          <hr>
        <% end %>
      <% end %>
    <% end %>
    <div class="order_total">
      <div class="order_total_content text-md-right">
        <div class="order_total_title">Order Total:</div>
        <div class="order_total_amount"><%= number_to_currency(cart_total) %></div>
      </div>
    </div>
  </ul>
</div>

app/views/shopping_carts/_shipping_form.html.erb
<%= simple_form_for @shipping, url: create_shipping_path, method: :post do |f| %>
  <div class="form-group row">
    <label class="form-label col-md-3">Contact Name:</label>
    <div class="col-md-9">
      <%= f.input :name, class: "form-control", label: false, required: true %>
    </div>
  </div>


  <div class="form-group row">
    <label class="form-label col-md-3">Street Address:</label>
    <div class="col-md-9">
      <div id="locationField">
        <%= f.input :street_address_one, class: "form-control", label: false, required: true, prompt: "Street address", :input_html => { :onFocus => "geolocate()", :id => "autocomplete"} %>
      </div>
      <%= f.input :street_address_two, class: "form-control", label: false, required: true, placeholder: "Apartment, suite, unit etc." %>
    </div>
  </div>

    <div id="address">
      <div class="form-group row">
        <label class="form-label col-md-3">Country/Region:</label>
      <div class="col-md-9">
        <%= f.input :cntry_name, class: "form-control", label: false, required: true, :input_html => { :id => "country"} %>
      </div>
      </div>

    <div class="form-group row">
      <label class="form-label col-md-3">State/Province:</label>
      <div class="col-md-9">
        <%= f.input :state, class: "form-control", label: false, required: true , :input_html => { :id => "administrative_area_level_1"}%>
      </div>
    </div>

    <div class="form-group row">
      <label class="form-label col-md-3">City:</label>
      <div class="col-md-9">
        <%= f.input :city, class: "form-control", label: false, required: true, :input_html => { :id => "locality"} %>
      </div>
    </div>

    <div class="form-group row">
      <label class="form-label col-md-3">Zip/Postal Code:</label>
      <div class="col-md-9">
        <%= f.input :postal_code, class: "form-control", label: false, required: true , :input_html => { :id => "postal_code"}%>
      </div>
    </div>

  </div>

  <div class="form-group row">
    <label class="form-label col-md-3">Mobile:</label>
    <div class="col-md-9">
      <%= f.input :mobile, class: "form-control", label: false, required: true, id: "mobile_no" %>
    </div>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= hidden_field_tag "value", "review_order" %>

  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <div class="cart_buttons" id="shipping_form_button">
        <%= link_to "Cancel", shop_path, class: "button cart_button_clear" %>
        <%= f.submit 'Submit', class: "button cart_button_checkout" %>
      </div>
    </div>
  </div>
<% end %>

app/views/shopping_carts/checkout.html.erb
<div class="cart_section">
  <div class="container">
    <%= render "checkout_order_states" %>
    <div id="review-order-panel">
      <%= render "order_address" %>
      <div class="row" id="form-inputs-group">
        <div class="col-lg-6 offset-lg-1">
          <%= render "shipping_form" %>
          </div>
      </div>
    </div>
    <div id="payment-done-panel">
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <div class="thanksforshoping">
            <img src="/assets/char_1.png" alt="">
            <p>Thanks for shoping with us</p>
          </div>
        </div>
      </div>
    </div>
    <% if @value != "done" %>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <div class="cart_container">
            <%= render "review_order" %>
            <%= render "order_payment" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% if current_user.shipping.nil? %>
  <style>
    #address-group-penal{
      display: none;
    }
    #form-inputs-group{
      display: block;
    }
  </style>
<% end %>
<% if current_user.present? && current_user.shipping.present? %>
  <style>
    #address-group-penal{
      display: block;
    }
    #form-inputs-group{
      display: none;
    }
      #continue_to_payment{
        display: block;
      }
      #shipping_form_button{
        display: none;
      }
  </style>
  <% else %>
  <style>
    #continue_to_payment{
      display: none;
    }
    #shipping_form_button{
      display: block;
    }
  </style>
<% end %>
<style>
  .form_border {
    border-color: #28a745
  }
.date select.date.form-control {
  width: auto;
}
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/13.0.2/js/intlTelInput.js"></script>
<script>
    $( document ).ready(function() {
        $('#month_input').val($('#date_month').val());
        $('#year_input').val($('#date_year').val());
        $('#date_month').on('change', function() {
            $('#month_input').val( this.value );
        });
        $('#date_year').on('change', function() {
            $('#year_input').val( this.value );
        });
        $(".progress-bar").css("flex-direction", "row");
        $('.show-inputs-group').click(function () {
            $('#address-group-penal').hide('slow');
            $('#form-inputs-group').show('slow');
            $('#shipping_form_button').show('slow');
            $('#continue_to_payment').hide('slow');
        });
        $(document).ready(function () {
            var pro = document.getElementsByClassName('progress-bar');
            var liarray = pro[0].getElementsByTagName('li');
            for (var i = 0; i < liarray.length; i++) {
                if (i === 0 && liarray[i].className === 'progress-bar__steps current') {
                    $('#review-order-panel').show();
                    $('#payment-done-panel').hide();
                } else if (i === 1 && liarray[i].className === 'progress-bar__steps current') {
                    $('#review-order-panel').hide();
                    $('#payment-panel').show();
                    $('#payment-done-panel').hide();
                } else if (i === 2 && liarray[i].className === 'progress-bar__steps current') {
                    $('#review-order-panel').hide();
                    $('#payment-panel').hide();
                    $('#payment-done-panel').show();
                }
            }
        });

        function checkLuhn(input) {
            var sum = 0;
            var numdigits = input.length;
            var parity = numdigits % 2;
            for (var i = 0; i < numdigits; i++) {
                var digit = parseInt(input.charAt(i))
                if (i % 2 == parity) digit *= 2;
                if (digit > 9) digit -= 9;
                sum += digit;
            }
            return (sum % 10) == 0;
        };

        function detectCard(input) {
            var typeTest = 'undefined',
                ltest1 = 16,
                ltest2 = 16;
            if (/^4/.test(input)) {
                typeTest = 'visa';
                ltest1 = 13;
            } else if (/^5[1-5]/.test(input)) {
                typeTest = 'mastercard';
            } else if (/^3[4-7]/.test(input)) {
                typeTest = 'amex';
                ltest1 = 15;
                ltest2 = 15;
            } else if (/^6(011|4[4-9]|5)/.test(input)) {
                typeTest = 'discover';
            }
            return [typeTest, ltest1, ltest2];
        }


        $('input.cc').keyup(function () {
            var val = this.value,
                val = val.replace(/[^0-9]/g, ''),
                detected = detectCard(val),
                errorClass = '',
                luhnCheck = checkLuhn(val),
                valueCheck = (val.length == detected[1] || val.length == detected[2]);
            if (luhnCheck && valueCheck) {
                errorClass = 'verified';
            } else if (valueCheck || val.length > detected[2]) {
                errorClass = 'error';
            }

            $(this).attr('class', 'cc ' + detected[0] + ' ' + errorClass);
        });

        $("#card_info_card").addClass("cc");
        $("#shipping_mobile").intlTelInput({
            allowExtensions: true,
            autoFormat: true,
            autoHideDialCode: true,
            autoPlaceholder: true,
            preferredCountries: ['us', 'gb'],
            defaultCountry: 'auto',
            ipinfoToken: 'yolo',
            nationalMode: false,
            numberType: 'MOBILE',
            preventInvalidNumbers: true
        });
        var imageUrl = "/assets/flags@2x.png";
        $('.iti-flag').css('background-image', 'url(' + imageUrl + ')');
    });
</script>
<script>
    var placeSearch, autocomplete;
    var componentForm = {
        // street_number: 'short_name',
        // route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
    };

    function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
    }

    function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        for (var component in componentForm) {
            document.getElementById(component).value = '';
            document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
            var addressType = place.address_components[i].types[0];
            if (componentForm[addressType]) {
                var val = place.address_components[i][componentForm[addressType]];
                document.getElementById(addressType).value = val;
            }
        }
    }

    // Bias the autocomplete object to the user's geographical location,
    // as supplied by the browser's 'navigator.geolocation' object.
    function geolocate() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var geolocation = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };
                var circle = new google.maps.Circle({
                    center: geolocation,
                    radius: position.coords.accuracy
                });
                autocomplete.setBounds(circle.getBounds());
            });
        }
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC4c-wNONsOUCrHcva6LSl6Yznh1ZKPA-s&libraries=places&callback=initAutocomplete"
        async defer></script>