config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    resources :brands, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :product_types, only: [:index, :new, :create]
    resources :users, only: [:index]
    resources :conversations, only: [:index, :new, :show]
    resources :personal_messages, only: [:new, :create]
    resources :orders, only: [] do
      collection do
        get :unpaid_orders
        get :paid_orders
        get :shipped_orders
      end
      member do
        get :ship_order
      end
    end
  end
  resources :shopping_carts, except: [:new, :create, :edit, :update, :destroy, :index, :show] do
    collection do
      get 'checkout'
      post 'process_payment'
      get 'remove_items_from_cart'
    end
  end
  resources :conversations
  resources :personal_messages

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", passwords: 'users/passwords' }
  root to: 'home#index'
  get 'home/shop' => "home#shop", as: :shop
  get 'home/sub_categories' => "home#sub_categories", as: :sub_categories
  get 'home/product_types' => "home#product_types", as: :product_types
  get 'home/product' => "home#product", as: :product
  get 'home/cart' => "home#cart", as: :cart
  get 'home/contact' => "home#contact", as: :contact
  get 'home/blog' => "home#blog", as: :blog
  get 'home/blog_show' => "home#blog_show", as: :blog_show
  get 'home/add_favorite' => "home#add_favorite", as: :add_favorite
  get 'home/remove_favorite' => "home#remove_favorite", as: :remove_favorite
  get 'home/my_favorites' => "home#my_favorites", as: :my_favorites
  get 'home/add_to_cart' => "home#add_to_cart", as: :add_to_cart
  post 'home/create_shipping' => "home#create_shipping", as: :create_shipping
  get 'home/product_detail_modal' => "home#product_detail_modal", as: :product_detail_modal
  get 'home/about_us' => "home#about_us", as: :about_us
  get 'home/contact_us' => "home#contact_us", as: :contact_us
  get 'home/terms_of_use' => "home#terms_of_use", as: :terms_of_use
  get 'home/discount_policy' => "home#discount_policy", as: :discount_policy
  get 'home/return' => "home#return", as: :return
  get 'home/privacy_policy' => "home#privacy_policy", as: :privacy_policy
  get 'home/shipping_help' => "home#shipping_help", as: :shipping_help
  get 'home/see_all' => 'home#see_all'
  resources :dashboards do
    collection do
      get :order_shipping_details
    end
  end

  get 'catergory_list' => "dashboards#catergory_list", as: :catergory_list
  get 'add_catergory' => "dashboards#add_catergory", as: :add_catergory
  post 'create_catergory' => "dashboards#create_catergory", as: :create_catergory
  get 'edit_category' => "dashboards#edit_category", as: :edit_category
  put 'update_category' => "dashboards#update_category", as: :update_category

  get 'sub_category_list' => "dashboards#sub_category_list", as: :sub_category_list
  get 'add_sub_category' => "dashboards#add_sub_category", as: :add_sub_category
  post 'create_sub_category' => "dashboards#create_sub_category", as: :create_sub_category

  get 'store' => "dashboards#store", as: :store
  get 'add_store' => "dashboards#add_store", as: :add_store
  post 'create_store' => "dashboards#create_store", as: :create_store

  get 'product_list' => "dashboards#product_list", as: :product_list
  get 'add_product' => "dashboards#add_product", as: :add_product
  post 'create_product' => "dashboards#create_product", as: :create_product
  get 'edit_product' => "dashboards#edit_product", as: :edit_product
  put 'update_product' => "dashboards#update_product", as: :update_product
  get 'delete_product' => "dashboards#delete_product", as: :delete_product

  get 'product_color_list' => "dashboards#product_color_list", as: :product_color_list
  get 'add_product_color' => "dashboards#add_product_color", as: :add_product_color
  post 'create_product_color' => "dashboards#create_product_color", as: :create_product_color

  get 'product_size_list' => "dashboards#product_size_list", as: :product_size_list
  get 'add_product_size' => "dashboards#add_product_size", as: :add_product_size
  post 'create_product_size' => "dashboards#create_product_size", as: :create_product_size

  get 'closure_type_list' => "dashboards#closure_type_list", as: :closure_type_list
  get 'add_closure_type' => "dashboards#add_closure_type", as: :add_closure_type
  post 'create_closure_type' => "dashboards#create_closure_type", as: :create_closure_type


  get 'collar_list' => "dashboards#collar_list", as: :collar_list
  get 'add_collar_type' => "dashboards#add_collar_type", as: :add_collar_type
  post 'create_collar_type' => "dashboards#create_collar_type", as: :create_collar_type

  get 'craft_list' => "dashboards#craft_list", as: :craft_list
  get 'add_craft_type' => "dashboards#add_craft_type", as: :add_craft_type
  post 'create_craft_type' => "dashboards#create_craft_type", as: :create_craft_type


  get 'design_list' => "dashboards#design_list", as: :design_list
  get 'add_design' => "dashboards#add_design", as: :add_design
  post 'create_design' => "dashboards#create_design", as: :create_design

  get 'design_type_list' => "dashboards#design_type_list", as: :design_type_list
  get 'add_design_type' => "dashboards#add_design_type", as: :add_design_type
  post 'create_design_type' => "dashboards#create_design_type", as: :create_design_type

  get 'pattern_style_list' => "dashboards#pattern_style_list", as: :pattern_style_list
  get 'add_pattern_style' => "dashboards#add_pattern_style", as: :add_pattern_style
  post 'create_pattern_style' => "dashboards#create_pattern_style", as: :create_pattern_style


  get 'sleeve_type_list' => "dashboards#sleeve_type_list", as: :sleeve_type_list
  get 'add_sleeve_type' => "dashboards#add_sleeve_type", as: :add_sleeve_type
  post 'create_sleeve_type' => "dashboards#create_sleeve_type", as: :create_sleeve_type


  get 'styles_list' => "dashboards#styles_list", as: :styles_list
  get 'add_style' => "dashboards#add_style", as: :add_style
  post 'create_style' => "dashboards#create_style", as: :create_style

  get 'shipping_prices' => "dashboards#shipping_prices", as: :shipping_prices
  get 'add_shipping_prices' => "dashboards#add_shipping_prices", as: :add_shipping_prices
  post 'create_shipping_price' => "dashboards#create_shipping_price", as: :create_shipping_price

  get 'orders_list' => "dashboards#orders_list", as: :orders_list
  get 'pending_orders' => "dashboards#pending_orders", as: :pending_orders
  get 'completed_orders' => "dashboards#completed_orders", as: :completed_orders
  get 'order_details' => "dashboards#order_details", as: :order_details
  get 'my_order_details' => "dashboards#my_order_details", as: :my_order_details
  get 'change_product_status' => "dashboards#change_product_status", as: :change_product_status
  get 'change_order_status' => "dashboards#change_order_status", as: :change_order_status
  mount ActionCable.server => '/cable'

  #For static pages
  get "/pages/:page" => "pages#show"
  resources :states, only: :index
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  require 'will_paginate/array'

  def index
    @products = Product.paginate(page: params[:page], per_page: 10).order('created_at DESC').includes(:product_images)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def shop
    if params[:category].present?
      ids = ProductCategory.where(category_id: params[:category]).pluck(:product_id)
      @products = Product.includes([:category, :sub_category, :product_images]).where("id IN (?)", ids).order(:price).paginate(:page => params[:page], :per_page => 30)
      @category = Category.where(id: params[:category]).first.name
    elsif params[:sub_category].present?
      ids = ProductSubCategory.where(sub_category_id: params[:sub_category]).pluck(:product_id)
      @products = Product.where("id IN (?)", ids).order(:price).paginate(:page => params[:page], :per_page => 30)
      @category = SubCategory.where(id: params[:sub_category]).first.name
    elsif params[:product_type].present?
      ids = ProductGroup.where(product_type_id: params[:product_type]).pluck(:product_id)
      @products = Product.where("id IN (?)", ids).order(:price).paginate(:page => params[:page], :per_page => 30)
      @category = ProductType.where(id: params[:product_type]).first.name
    elsif params[:brand_id].present?
      ids = ProductBrand.where(brand_id: params[:brand_id]).pluck(:product_id)
      @products = Product.where("id IN (?)", ids).order(:price).paginate(:page => params[:page], :per_page => 30)
      @category = Brand.where(id: params[:brand_id]).first.name
    elsif params[:search_product].present? && params[:search_product][:keyword].present? && params[:search_product][:category].present?
      ids = ProductCategory.where(category_id: params[:search_product][:category]).pluck(:product_id)
      products = Product.where("id IN (?)", ids)
      @products = products.where("name ILIKE ?", "%" + params[:search_product][:keyword] + "%").order(:price).paginate(:page => params[:page], :per_page => 16)
    elsif params[:search_product].present? && params[:search_product][:keyword].present?
      @products = []
      categories = Category.where("name ILIKE ?", "%" + params[:search_product][:keyword] + "%")
      categories.each do |category|
        @products << category.products
      end
      sub_categories = SubCategory.where("name ILIKE ?", "%" + params[:search_product][:keyword] + "%")
      sub_categories.each do |sub_category|
        @products << sub_category.products
      end
      product_type = ProductType.where("name ILIKE ?", "%" + params[:search_product][:keyword] + "%")
      product_type.each do |pro_type|
        @products << pro_type.products
      end
      @products << Product.where("name ILIKE ? OR description ILIKE ?", "%" + params[:search_product][:keyword] + "%", "%" + params[:search_product][:keyword] + "%")
      @products = @products.flatten.uniq
      @products = @products.sort_by { |product| [product.price] }
      @products = @products.paginate(:page => params[:page], :per_page => 30)

    elsif params[:search_product].present? && params[:search_product][:category].present?
      ids = ProductCategory.where(category_id: params[:search_product][:category]).pluck(:product_id)
      @products = Product.where("id IN (?)", ids).order(:price).paginate(:page => params[:page], :per_page => 30)
    else
      @products = Product.all.order(:price).paginate(:page => params[:page], :per_page => 30)
      if @products.present?
        @category = @products.last.category.name
      end
    end
    if @products.present?
      @sub_categories = @products.last.category.sub_categories
      @product_types = @products.last.sub_category.product_types if @products.last.sub_category.present?
    end
    render layout: "shop_application"
  end

  def sub_categories
    if params[:category].present?
      @category = Category.includes(:sub_categories, :products).find(params[:category])
      @sub_categories = @category.sub_categories
      @products = @category.products.paginate( page: params[:page], per_page: 48)
    elsif params[:sub_category].present?
      @sub_category = SubCategory.includes([:product_types, :products]).find(params[:sub_category])
      @product_types = @sub_category.product_types
      @products = @sub_category.products.paginate( page: params[:page], per_page: 48)
    else
      @product_type = ProductType.includes(:sub_category, :products).where(id:params[:product_type]).take
      @sub_category = @product_type.sub_category
      @parent_product_type = @product_type.parent_product_type
      @products = @product_type.products.paginate(page: params[:page], per_page: 48)
    end
    render layout: "shop_application", collection: @sub_categories
  end

  def product_types
    if params[:sub_category].present?
      @product_types = ProductType.where(sub_category_id: params[:sub_category]).limit(5)
    else
      redirect_to root_path
    end
    render layout: "shop_application"
  end

  def product
    @product = Product.includes([:product_images, :sub_category, :category]).find(params[:id])
    @related_products = @product.product_type.products
    if ShippingPrice.all.count > 0
      @product_shipping = ShippingPrice.first.price
    end
    if @product.sizes.present?
      @product_size = @product.sizes.first.name
    end
    if @product.colors.present?
      @product_colors = @product.colors.first.name
    end
    if current_user.present?
      recent_viewed = RecentView.where(user_id: current_user.id, product_id: params[:id])
      if recent_viewed.present?
      else
        RecentView.create(user_id: current_user.id, product_id: params[:id])
      end
    else
      session[:recent_views] ||= []
      if session[:recent_views].nil?
        session[:recent_views] << ""
        session[:recent_views] << params[:id].to_i
      else
        session[:recent_views] << params[:id].to_i
      end
      puts session[:recent_views]
    end
    render layout: "product_application"
  end

  def cart
    current_user.present? && current_user.orders.where(status: "pending").present? ? @order_items = current_user.orders.where(status: "pending").last.order_items : @order_items = []
    render layout: "cart_application"
  end

  def create_shipping
    if current_user.shipping.present?
      current_user.shipping.update_attributes(shipping_params)
    else
      shipping  = Shipping.create(shipping_params)
    end
    redirect_to  checkout_shopping_carts_path(value: "review_order")
  end

  def product_detail_modal
    @product= Product.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def contact
    render layout: "contact_application"
  end

  def blog
    render layout: "blog_application"
  end

  def blog_show
    render layout: "blog_single_application"
  end

  def add_favorite
    @product_id = params[:product_id]
    if current_user.present?
      favorite = UserFavorite.where(user_id: current_user.id, product_id: params[:product_id])
      if favorite.present?
        # do nothing
      else
        UserFavorite.create(user_id: current_user.id, product_id: params[:product_id])
      end
    else
      # session.delete(:favorites)
      session[:favorites] ||= []
      if session[:favorites].nil?
        session[:favorites] << ""
        session[:favorites] << params[:product_id].to_i
      else
        session[:favorites] << params[:product_id].to_i
      end
    end
    respond_to do |format|
      format.js
    end
    render layout: "product_application"
  end

  def remove_favorite
    @product_id = params[:product_id]
    if current_user.present?
      favorite = UserFavorite.where(user_id: current_user.id, product_id: params[:product_id])
      if favorite.present?
        favorite.first.destroy
      end
    else
      session[:favorites].delete(params[:product_id].to_i)
    end
    respond_to do |format|
      format.js
    end
  end

  def my_favorites
    if current_user.present?
      favorites_ids = current_user.user_favorites.pluck(:product_id)
      @products = Product.where("id IN (?)", favorites_ids).paginate(:page => params[:page], :per_page => 10)
    else
      if !session[:favorites].nil?
        @products = Product.where("id IN (?)", session[:favorites]).paginate(:page => params[:page], :per_page => 10)
      else
        @products = Product.where("id IN (?)", []).paginate(:page => params[:page], :per_page => 10)
      end
    end
    render layout: "shop_application"
  end

  def add_to_cart
    if current_user.present?
      order = Order.where(user_id: current_user.id, status: "pending")
      if order.present?
        order_id = order.last.id
      else
        order = Order.create(user_id: current_user.id)
        order_id = order.id
      end
      order_item = OrderItem.create(product_id: params[:add_product_to_cart][:product_id], quantity: params[:add_product_to_cart][:quantity], order_id: order_id, size: params[:add_product_to_cart][:size], color: params[:add_product_to_cart][:color], shipping: params[:add_product_to_cart][:shipping])
    else
      # session.delete(:favorites)
      product_array = [params[:add_product_to_cart][:product_id], params[:add_product_to_cart][:quantity], params[:add_product_to_cart][:size], params[:add_product_to_cart][:color], params[:add_product_to_cart][:shipping]]
      session[:shop_cart] ||= []
      if session[:shop_cart].nil?
        session[:shop_cart] << ""
        session[:shop_cart] << product_array
      else
        session[:shop_cart] << product_array
      end
    end
    flash[:notice] = 'Product added to cart successfully!'
    redirect_to request.referer
  end

  def about_us
    render layout: "blog_single_application"
  end

  def contact_us
    render layout: "blog_single_application"
  end

  def terms_of_use
    render layout: "blog_single_application"
  end

  def discount_policy

app/helpers/home_helper.rb
module HomeHelper
  def get_t_shirts
    ProductType.where(name:"T-Shirts").take.products.includes(:product_images)
  end

  def get_blazers
    ProductType.where(name:"Blazers").take.products.includes(:product_images)
  end

  def get_car_lights
    ProductType.where(name:"Car Lights").take.products.includes(:product_images)
  end

  def get_men_shirts
    ProductType.where(name:"Shirts").take.products.includes(:product_images)
  end

  def get_men_jeans
    Category.where(name:"Men’s Clothing").take.sub_categories.where(name:"Bottoms").take.product_types.where(name:"Jeans").take.products.includes(:product_images)
  end

  def get_men_under_garments
    ProductType.where(name:"Boxers").take.products.includes(:product_images)
  end

  def product_types? sub_category
    sub_category.product_types.present?
  end
end

app/views/home/_sub_categories.html.erb
<div class = "row d-none d-sm-block">
  <div class=  "float-left ml-5" >
    <div>
      <%= link_to @category.name, sub_categories_path(category: @category.id) %> >
    </div>
    <% @sub_categories.each do |sub_category| %>
    <ol class = "pl-5"> <%= link_to sub_category.name, sub_categories_path(sub_category: sub_category.id) %></ol>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="row">
  <div class= "col-12 ml-auto col-lg-12">
    <div class="row">
      <% @products.each do |product| %>
        <div class="col-lg-3 col-6">
          <div class="product_item is_new" id="product_<%= product.id %>">
            <%= link_to product_path(id: product.id) do %>
              <div class="product_image d-flex flex-column align-items-center justify-content-center mt-5">
                <img src="<%= product.product_images.first.image.url(:original) if product.product_images.present? %>" alt="">
                <img src="<%= product.product_images.second.image.url(:original) if product.product_images.present? && product.product_images.second.present? %>" alt="">
              </div>
            <% end %>
            <div class="product_content mt-5">
              <div class="product_name">
                <div>
                  <a href="<%= product_path(id: product.id) %>" tabindex="0"><%= product.name %></a>
                </div>
              </div>
              <div class="product_price">$<%= product.price %></div>
            </div>
            <% if check_favorite(product.id) == true %>
              <%= link_to remove_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                <div class="product_fav active" id="<%= "in_product_#{product.id}"%>">
                  <i class="fas fa-heart"></i>
                </div>
              <% end %>
            <% else %>
              <%= link_to add_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                <div class="product_fav" id="<%= "in_product_#{product.id}"%>">
                  <i class="fas fa-heart"></i>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>
</div>
</div>
<%= will_paginate @products %>
</div>
<style type="text/css">
@media screen and (min-height: 550px) {
.product_item {
  display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    position: relative;
    width: 100%;
    background: #FFFFFF;
    cursor: pointer;
    padding-top: 40px;
    padding-bottom: 24px;
    text-align: center;
    padding-right: 15px
}
.product_image img {
    display: block;
    position: relative;
    max-width: 100%;
}
.product_image {
    width: 100%;
    height: auto;
}
.product_content {
  width: 100%;
}
.product_price {
    font-size: 16px;
    margin-top: 25px;
    color: #f60;
    font-weight: 700;
}
.product_name {
    margin-top: 4px;
    overflow: hidden;
}
.product_name div 
a {
    font-size: 14px;
    font-weight: 400;
    color: #000000;
    white-space: initial; 
    transition: all 200ms ease;
}
.product_name div {
    width: 100%;
}
}
@media screen and (max-width: 300px) {
  .product_item {
    padding-top: 0;
    width: 80px;
  }
  .product_image {
    height: 0;
  }
  .product_price {
    font-size: 10px;
    color: #f60;
  }
  }
</style>

app/views/home/add_favorite.js.erb
toastr.success('Added to favorites successfully');
console.log("<%= @product_id %>");
var product_id = "<%= @product_id %>";
var un_fav_link = "<%= "/home/remove_favorite?product_id=#{@product_id}" %>";
$("#in_product_"+product_id).addClass("active");
$("#in_product_"+product_id).closest('a').attr("href", un_fav_link);

app/views/home/blog_show.html.erb
<div class="home">
  <section class="home">
    <div class="home_background parallax-window" data-parallax="scroll" data-image-src="/assets/blog_single_background.jpg" data-speed="0.8"><img  src="/assets/blog_single_background.jpg"></div>
  </section>

</div>

<!-- Single Blog Post -->

<div class="single_post">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <div class="single_post_title">Vivamus sed nunc in arcu cursus mollis quis et orci. Interdum et malesuada</div>
        <div class="single_post_text">
          <p>Mauris viverra cursus ante laoreet eleifend. Donec vel fringilla ante. Aenean finibus velit id urna vehicula, nec maximus est sollicitudin. Praesent at tempus lectus, eleifend blandit felis. Fusce augue arcu, consequat a nisl aliquet, consectetur elementum turpis. Donec iaculis lobortis nisl, et viverra risus imperdiet eu. Etiam mollis posuere elit non sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis arcu a magna sodales venenatis. Integer non diam sit amet magna luctus mollis ac eu nisi. In accumsan tellus ut dapibus blandit.</p>

          <div class="single_post_quote text-center">
            <div class="quote_image"><img src="/assets/quote.png" alt=""></div>
            <div class="quote_text">Quisque sagittis non ex eget vestibulum. Sed nec ultrices dui. Cras et sagittis erat. Maecenas pulvinar, turpis in dictum tincidunt, dolor nibh lacinia lacus.</div>
            <div class="quote_name">Liam Neeson</div>
          </div>

          <p>Praesent ac magna sed massa euismod congue vitae vitae risus. Nulla lorem augue, mollis non est et, eleifend elementum ante. Nunc id pharetra magna.  Praesent vel orci ornare, blandit mi sed, aliquet nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Blog Posts -->

<div class="blog">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="blog_posts d-flex flex-row align-items-start justify-content-between">

          <!-- Blog post -->
          <div class="blog_post">
            <div class="blog_image" style="background-image:url(/assets/blog_4.jpg)"></div>
            <div class="blog_text">Etiam leo nibh, consectetur nec orci et, tempus tempus ex</div>
            <div class="blog_button"><a href="blog_single.html">Continue Reading</a></div>
          </div>

          <!-- Blog post -->
          <div class="blog_post">
            <div class="blog_image" style="background-image:url(/assets/blog_5.jpg)"></div>
            <div class="blog_text">Sed viverra pellentesque dictum. Aenean ligula justo, viverra in lacus porttitor</div>
            <div class="blog_button"><a href="blog_single.html">Continue Reading</a></div>
          </div>

          <!-- Blog post -->
          <div class="blog_post">
            <div class="blog_image" style="background-image:url(/assets/blog_6.jpg)"></div>
            <div class="blog_text">In nisl tortor, tempus nec ex vitae, bibendum rutrum mi. Integer tempus nisi</div>
            <div class="blog_button"><a href="blog_single.html">Continue Reading</a></div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/contact_us.html.erb
<div class="home">
  <section class="home">
    <div class="home_background parallax-window" data-parallax="scroll" data-image-src="/assets/blog_single_background.jpg" data-speed="0.8"><img  src="/assets/blog_single_background.jpg"></div>
  </section>

</div>

<!-- Single Blog Post -->

<div class="single_post">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <div class="single_post_title">Contact us</div>
        <div class="single_post_title">Customer Service
        </div>
        <div class="single_post_text">
          <p>Support on facebook <a href="https://www.messenger.com/t/473678129767681" target="_blank">Click here</a></p>
          <p>Service by Phone: <a href="tel:+16266150262">Click here</a>

          </p>
        </div>
      </div>
      <div class="col-lg-8 offset-lg-2">
        <div class="single_post_title">Link Requests</div>
        <div class="single_post_text">
          <p>For information and requests regarding link submission to our resources directory <a href="mailto:talotsing@gmail.com" target="_top">Click here</a>
          </p>

        </div>
      </div>
      <div class="col-lg-8 offset-lg-2">
        <div class="single_post_title">Product Suggestions
        </div>
        <div class="single_post_text">
          <p>We welcome your suggestions. If there is a product you think we should make available, please <a href="mailto:talotsing@gmail.com" target="_top">Click here</a> to tell us about it
          </p>
          <p>1407 Fulton St, Brooklyn
          </p>
          <p>Brooklyn, NY 11216
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/discount_policy.html.erb
<div class="home">
  <section class="home">
    <div class="home_background parallax-window" data-parallax="scroll" data-image-src="/assets/blog_single_background.jpg" data-speed="0.8"><img  src="/assets/blog_single_background.jpg"></div>
  </section>

</div>

<!-- Single Blog Post -->

<div class="single_post">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <div class="single_post_title">Discount Policy
        </div>

        <div class="single_post_text">
          <p>Warmly notice:</p>
          <p>But we can still provide some discounts for the big orders in order to give our customers a support and favor. Welcome to contact with us for details if you have a big order or some other good ideas. Thanks!</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/see_all.html.erb
<div class = "container">
  <% @categories.each do |category| %>
    <div class = "row">
      <div class = "col-12">
        <h3> <%= category.see_all_name %> </h3>
      </div>
    </div>
    <% category.sub_categories.each do |sub_category| %>
      <div class = "row">
      <% sub_category.product_types.order(:see_all_order).each do |product_type| %>
        <div class = "col-lg-4">
          <% if product_type.see_all %>
            <%= link_to product_type.name, shop_path(product_type: product_type.id), style:"font-size:1.5em" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <% end %>
    <hr>
  <% end %>
</div>

app/views/home/sub_categories.html.erb
<div class="shop">
  <% if @category.present? %>
    <%= render "sub_categories" %>
  <% elsif @product_types.present? %>
    <%= render "product_types" %>
  <% else %>
    <%= render "selected_products" %>
  <% end %>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    setHeader();
    function setHeader()
      {
        var controller = new ScrollMagic.Controller(
          {
            globalSceneOptions:
            {
              triggerHook: 'onLeave'
            }
          });
        var pin = new ScrollMagic.Scene(
        {
          triggerElement: '.main_nav'
        })
        .setPin('.main_nav').addTo(controller);
        if(window.innerWidth > 991 && menuActive)
        {
          closeMenu();
        }
      }
  })
</script>