config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    resources :brands, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :product_types, only: [:index, :new, :create]
    resources :users, only: [:index]
    resources :conversations, only: [:index, :new, :show]
    resources :personal_messages, only: [:new, :create]
    resources :orders, only: [] do
      collection do
        get :unpaid_orders
        get :paid_orders
        get :shipped_orders
      end
      member do
        get :ship_order
      end
    end
  end
  resources :shopping_carts, except: [:new, :create, :edit, :update, :destroy, :index, :show] do
    collection do
      get 'checkout'
      post 'process_payment'
      get 'remove_items_from_cart'
    end
  end
  resources :conversations
  resources :personal_messages

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", passwords: 'users/passwords' }
  root to: 'home#index'
  get 'home/shop' => "home#shop", as: :shop
  get 'home/sub_categories' => "home#sub_categories", as: :sub_categories
  get 'home/product_types' => "home#product_types", as: :product_types
  get 'home/product' => "home#product", as: :product
  get 'home/cart' => "home#cart", as: :cart
  get 'home/contact' => "home#contact", as: :contact
  get 'home/blog' => "home#blog", as: :blog
  get 'home/blog_show' => "home#blog_show", as: :blog_show
  get 'home/add_favorite' => "home#add_favorite", as: :add_favorite
  get 'home/remove_favorite' => "home#remove_favorite", as: :remove_favorite
  get 'home/my_favorites' => "home#my_favorites", as: :my_favorites
  get 'home/add_to_cart' => "home#add_to_cart", as: :add_to_cart
  post 'home/create_shipping' => "home#create_shipping", as: :create_shipping
  get 'home/product_detail_modal' => "home#product_detail_modal", as: :product_detail_modal
  get 'home/about_us' => "home#about_us", as: :about_us
  get 'home/contact_us' => "home#contact_us", as: :contact_us
  get 'home/terms_of_use' => "home#terms_of_use", as: :terms_of_use
  get 'home/discount_policy' => "home#discount_policy", as: :discount_policy
  get 'home/return' => "home#return", as: :return
  get 'home/privacy_policy' => "home#privacy_policy", as: :privacy_policy
  get 'home/shipping_help' => "home#shipping_help", as: :shipping_help
  get 'home/see_all' => 'home#see_all'
  resources :dashboards do
    collection do
      get :order_shipping_details
    end
  end

  get 'catergory_list' => "dashboards#catergory_list", as: :catergory_list
  get 'add_catergory' => "dashboards#add_catergory", as: :add_catergory
  post 'create_catergory' => "dashboards#create_catergory", as: :create_catergory
  get 'edit_category' => "dashboards#edit_category", as: :edit_category
  put 'update_category' => "dashboards#update_category", as: :update_category

  get 'sub_category_list' => "dashboards#sub_category_list", as: :sub_category_list
  get 'add_sub_category' => "dashboards#add_sub_category", as: :add_sub_category
  post 'create_sub_category' => "dashboards#create_sub_category", as: :create_sub_category

  get 'store' => "dashboards#store", as: :store
  get 'add_store' => "dashboards#add_store", as: :add_store
  post 'create_store' => "dashboards#create_store", as: :create_store

  get 'product_list' => "dashboards#product_list", as: :product_list
  get 'add_product' => "dashboards#add_product", as: :add_product
  post 'create_product' => "dashboards#create_product", as: :create_product
  get 'edit_product' => "dashboards#edit_product", as: :edit_product
  put 'update_product' => "dashboards#update_product", as: :update_product
  get 'delete_product' => "dashboards#delete_product", as: :delete_product

  get 'product_color_list' => "dashboards#product_color_list", as: :product_color_list
  get 'add_product_color' => "dashboards#add_product_color", as: :add_product_color
  post 'create_product_color' => "dashboards#create_product_color", as: :create_product_color

  get 'product_size_list' => "dashboards#product_size_list", as: :product_size_list
  get 'add_product_size' => "dashboards#add_product_size", as: :add_product_size
  post 'create_product_size' => "dashboards#create_product_size", as: :create_product_size

  get 'closure_type_list' => "dashboards#closure_type_list", as: :closure_type_list
  get 'add_closure_type' => "dashboards#add_closure_type", as: :add_closure_type
  post 'create_closure_type' => "dashboards#create_closure_type", as: :create_closure_type


  get 'collar_list' => "dashboards#collar_list", as: :collar_list
  get 'add_collar_type' => "dashboards#add_collar_type", as: :add_collar_type
  post 'create_collar_type' => "dashboards#create_collar_type", as: :create_collar_type

  get 'craft_list' => "dashboards#craft_list", as: :craft_list
  get 'add_craft_type' => "dashboards#add_craft_type", as: :add_craft_type
  post 'create_craft_type' => "dashboards#create_craft_type", as: :create_craft_type


  get 'design_list' => "dashboards#design_list", as: :design_list
  get 'add_design' => "dashboards#add_design", as: :add_design
  post 'create_design' => "dashboards#create_design", as: :create_design

  get 'design_type_list' => "dashboards#design_type_list", as: :design_type_list
  get 'add_design_type' => "dashboards#add_design_type", as: :add_design_type
  post 'create_design_type' => "dashboards#create_design_type", as: :create_design_type

  get 'pattern_style_list' => "dashboards#pattern_style_list", as: :pattern_style_list
  get 'add_pattern_style' => "dashboards#add_pattern_style", as: :add_pattern_style
  post 'create_pattern_style' => "dashboards#create_pattern_style", as: :create_pattern_style


  get 'sleeve_type_list' => "dashboards#sleeve_type_list", as: :sleeve_type_list
  get 'add_sleeve_type' => "dashboards#add_sleeve_type", as: :add_sleeve_type
  post 'create_sleeve_type' => "dashboards#create_sleeve_type", as: :create_sleeve_type


  get 'styles_list' => "dashboards#styles_list", as: :styles_list
  get 'add_style' => "dashboards#add_style", as: :add_style
  post 'create_style' => "dashboards#create_style", as: :create_style

  get 'shipping_prices' => "dashboards#shipping_prices", as: :shipping_prices
  get 'add_shipping_prices' => "dashboards#add_shipping_prices", as: :add_shipping_prices
  post 'create_shipping_price' => "dashboards#create_shipping_price", as: :create_shipping_price

  get 'orders_list' => "dashboards#orders_list", as: :orders_list
  get 'pending_orders' => "dashboards#pending_orders", as: :pending_orders
  get 'completed_orders' => "dashboards#completed_orders", as: :completed_orders
  get 'order_details' => "dashboards#order_details", as: :order_details
  get 'my_order_details' => "dashboards#my_order_details", as: :my_order_details
  get 'change_product_status' => "dashboards#change_product_status", as: :change_product_status
  get 'change_order_status' => "dashboards#change_order_status", as: :change_order_status
  mount ActionCable.server => '/cable'

  #For static pages
  get "/pages/:page" => "pages#show"
  resources :states, only: :index
end

app/models/product.rb
class Product < ApplicationRecord
  self.per_page = 10
  belongs_to :store

  has_many :product_colors, dependent: :destroy
  has_many :colors ,through: :product_colors

  has_many :product_sizes, dependent: :destroy
  has_many :sizes ,through: :product_sizes

  has_many :product_collars, dependent: :destroy
  has_many :collars ,through: :product_collars

  has_many :product_closure_types, dependent: :destroy
  has_many :closure_types ,through: :product_closure_types

  has_many :product_crafts, dependent: :destroy
  has_many :crafts ,through: :product_crafts

  has_many :product_designs, dependent: :destroy
  has_many :designs ,through: :product_designs

  has_many :product_design_types, dependent: :destroy
  has_many :design_types ,through: :product_design_types

  has_many :product_pattern_styles, dependent: :destroy
  has_many :pattern_styles ,through: :product_pattern_styles

  has_many :product_sleeve_types, dependent: :destroy
  has_many :sleeve_types ,through: :product_sleeve_types

  has_many :product_styles, dependent: :destroy
  has_many :styles ,through: :product_styles

  has_one :product_brand, dependent: :destroy
  has_one :brand ,through: :product_brand

  has_one :product_category, dependent: :destroy
  has_one :category ,through: :product_category

  has_one :product_sub_category, dependent: :destroy
  has_one :sub_category ,through: :product_sub_category

  has_one :product_group, dependent: :destroy
  has_one :product_type ,through: :product_group

  has_many :user_favorites, dependent: :destroy
  has_many :users ,through: :user_favorites

  has_many :recent_views, dependent: :destroy
  has_many :users ,through: :recent_views

  has_many :product_images, dependent: :destroy

  has_many :product_shipments, dependent: :destroy
  accepts_nested_attributes_for :product_shipments,:reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true

  has_many :product_specifications, dependent: :destroy
  accepts_nested_attributes_for :product_specifications,:reject_if => lambda { |a| a[:spec_key].blank? }, :allow_destroy => true

  has_many :product_color_images, dependent: :destroy
  accepts_nested_attributes_for :product_color_images,:reject_if => lambda { |a| a[:color].blank? }, :allow_destroy => true

  has_many :order_items

  def self.search(params, current_user)
    products = where(store_id: current_user.store.id)
    puts products
    products = products.where("name like ?", "%#{params[:search]}%") if params[:search]
    products
  end

  def multiply_price
    if self.price < 10 then self.price *= 2 else self.price += 10 end
    self.price.round(2)
  end

end

app/models/product_type.rb
class ProductType < ApplicationRecord
  belongs_to :sub_category, counter_cache: true
  has_many :product_groups, dependent: :destroy
  has_many :products , through: :product_groups, dependent: :destroy
  belongs_to :parent_product_type, class_name: 'ProductType', foreign_key: :parent_product_type_id, optional: true
  has_many :child_product_types, class_name: 'ProductType', foreign_key: :parent_product_type_id

  has_attached_file :image, styles: {
      thumb: '100x100>',
      square: '200x200#',
      medium: '300x300>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/views/products/_best_sellers.html.erb
  <div class="best_sellers">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="tabbed_container">
            <div class="tabs clearfix tabs-right">
              <div class="new_arrivals_title">Hot Best Sellers</div>
              <ul class="clearfix">
                <li class="active">Baby Supplies</li>
                <li>Girl Kids Clothing</li>
                <li>Boy Kids Clothing</li>
              </ul>
              <div class="tabs_line"><span></span></div>
            </div>

            <div class="bestsellers_panel panel active">

              <!-- Best Sellers Slider -->

              <div class="bestsellers_slider slider">

                <!-- Best Sellers Item -->
                <% if SubCategory.find(264).products.present? %>
                  <% SubCategory.find(264).products.includes(:product_images).sample(6).each do |product| %>
                    <div class="bestsellers_item">
                      <div class="product_item is_new" id="product_<%= product.id %>">
                        <%= link_to product_detail_modal_path(id: product.id) , remote: true, :class=>"btn" do %>
                        <div class="product_image d-flex flex-column align-items-center justify-content-center">
                          <img src="<%= product.product_images.first.image.url(:original) if product.product_images.present? %>" alt="">
                          <img src="<%= product.product_images.second.image.url(:original) if product.product_images.present? && product.product_images.second.present? %>" alt="">
                        </div>
                        <% end %>
                        <div class="product_content">
                          <div class="product_price">$<%= product.price %></div>
                          <div class="product_name">
                            <div>
                              <a href="<%= product_path(id: product.id) %>" tabindex="0"><%= product.name %></a>
                            </div>
                          </div>
                        </div>
                        <% if check_favorite(product.id) == true %>
                          <%= link_to remove_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                            <div class="product_fav active" id="<%= "in_product_#{product.id}"%>">
                              <i class="fas fa-heart"></i>
                            </div>
                          <% end %>
                        <% else %>
                          <%= link_to add_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                            <div class="product_fav" id="<%= "in_product_#{product.id}"%>">
                              <i class="fas fa-heart"></i>
                            </div>
                          <% end %>
                        <% end %>
                        <ul class="product_marks">
                          <li class="product_mark product_discount">-25%</li>
                          <li class="product_mark product_new">new</li>
                        </ul>
                      </div>
                    </div>
                  <% end %>
                <% end %>


              </div>
            </div>

            <div class="bestsellers_panel panel">

              <!-- Best Sellers Slider -->

              <div class="bestsellers_slider slider">

                <!-- Best Sellers Item -->
                <% if SubCategory.find(264).products.present? %>
                  <% SubCategory.find(264).products.sample(6).each do |product| %>
                    <div class="bestsellers_item">
                      <div class="product_item is_new" id="product_<%= product.id %>">
                        <%= link_to product_detail_modal_path(id: product.id) , remote: true, :class=>"btn" do %>
                        <div class="product_image d-flex flex-column align-items-center justify-content-center">
                          <img src="<%= product.product_images.first.image.url(:original) if product.product_images.present? %>" alt="">
                          <img src="<%= product.product_images.second.image.url(:original) if product.product_images.present? && product.product_images.second.present? %>" alt="">
                        </div>
                        <% end %>
                        <div class="product_content">
                          <div class="product_price">$<%= product.price %></div>
                          <div class="product_name">
                            <div>
                              <a href="<%= product_path(id: product.id) %>" tabindex="0"><%= product.name %></a>
                            </div>
                          </div>
                        </div>
                        <% if check_favorite(product.id) == true %>
                          <%= link_to remove_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                            <div class="product_fav active" id="<%= "in_product_#{product.id}"%>">
                              <i class="fas fa-heart"></i>
                            </div>
                          <% end %>
                        <% else %>
                          <%= link_to add_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                            <div class="product_fav" id="<%= "in_product_#{product.id}"%>">
                              <i class="fas fa-heart"></i>
                            </div>
                          <% end %>
                        <% end %>
                        <ul class="product_marks">
                          <li class="product_mark product_discount">-25%</li>
                          <li class="product_mark product_new">new</li>
                        </ul>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>

            <div class="bestsellers_panel panel">

              <!-- Best Sellers Slider -->

              <div class="bestsellers_slider slider">

                <!-- Best Sellers Item -->
                <% if SubCategory.find(264).products.present? %>
                  <% SubCategory.find(264).products.sample(6).each do |product| %>
                    <div class="bestsellers_item">
                      <div class="product_item is_new" id="product_<%= product.id %>">
                        <%= link_to product_detail_modal_path(id: product.id) , remote: true, :class=>"btn" do %>
                        <div class="product_image d-flex flex-column align-items-center justify-content-center">
                          <img src="<%= product.product_images.first.image.url(:original) if product.product_images.present? %>" alt="">
                          <img src="<%= product.product_images.second.image.url(:original) if product.product_images.present? && product.product_images.second.present? %>" alt="">

                        </div>
                        <% end %>
                        <div class="product_content">
                          <div class="product_price">$<%= product.price %></div>
                          <div class="product_name">
                            <div>
                              <a href="<%= product_path(id: product.id) %>" tabindex="0"><%= product.name %></a>
                            </div>
                          </div>
                        </div>
                        <% if check_favorite(product.id) == true %>
                          <%= link_to remove_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                            <div class="product_fav active" id="<%= "in_product_#{product.id}"%>">
                              <i class="fas fa-heart"></i>
                            </div>
                          <% end %>
                        <% else %>
                          <%= link_to add_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                            <div class="product_fav" id="<%= "in_product_#{product.id}"%>">
                              <i class="fas fa-heart"></i>
                            </div>
                          <% end %>
                        <% end %>
                        <ul class="product_marks">
                          <li class="product_mark product_discount">-25%</li>
                          <li class="product_mark product_new">new</li>
                        </ul>
                      </div>
                    </div>
                  <% end %>
                <% end %>

              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

app/views/products/_featured.html.erb
          <!-- Featured -->
          <div class="featured col-7 col-lg-12">
            <div class="tabbed_container">
              <div class="tabs">
                <ul class="clearfix">
                  <li class="active">T-Shirts</li>
                  <li>Blazers</li>
                  <li>Car Lights</li>
                </ul>
                <div class="tabs_line"><span></span></div>
              </div>

              <!-- Product Panel -->
              <div class="product_panel panel active">
                <div class="featured_slider slider">

                  <!-- Slider Item -->
                  <% if get_t_shirts.present? %>
                    <% get_t_shirts.each do |product| %>
                      <div class="featured_slider_item">
                        <div class="product_item is_new" id="product_<%= product.id %>">
                          <%= link_to product_detail_modal_path(id: product.id) , remote: true, :class=>"btn" do %>
                          <div class="product_image d-flex flex-column align-items-center justify-content-center">
                            <img src="<%= product.product_images.first.image.url(:original) if product.product_images.present? %>" alt="">
                            <img src="<%= product.product_images.second.image.url(:original) if product.product_images.present? && product.product_images.second.present? %>" alt="">
                          </div>
                          <% end %>
                          <div class="product_content">
                            <div class="product_price">$<%= product.price %></div>
                            <div class="product_name">
                              <div>
                                <a href="<%= product_path(id: product.id) %>" tabindex="0"><%= product.name %></a>
                              </div>
                            </div>
                          </div>
                          <% if check_favorite(product.id) == true %>
                            <%= link_to remove_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                              <div class="product_fav active" id="<%= "in_product_#{product.id}"%>">
                                <i class="fas fa-heart"></i>
                              </div>
                            <% end %>
                          <% else %>
                            <%= link_to add_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                              <div class="product_fav" id="<%= "in_product_#{product.id}"%>">
                                <i class="fas fa-heart"></i>
                              </div>
                            <% end %>
                          <% end %>
                          <ul class="product_marks">
                            <li class="product_mark product_discount">-25%</li>
                            <li class="product_mark product_new">new</li>
                          </ul>
                        </div>
                      </div>
                    <% end %>
                  <% end %>

                </div>
                <div class="featured_slider_dots_cover"></div>
              </div>

              <!-- Product Panel -->
              <div class="product_panel panel">
                <div class="featured_slider slider">

                  <!-- Slider Item -->
                  <% if get_blazers.present? %>
                    <% get_blazers.each do |product| %>
                      <div class="featured_slider_item">
                        <div class="product_item is_new" id="product_<%= product.id %>">
                          <%= link_to product_detail_modal_path(id: product.id) , remote: true, :class=>"btn" do %>
                          <div class="product_image d-flex flex-column align-items-center justify-content-center">
                            <img src="<%= product.product_images.first.image.url(:original) if product.product_images.present? %>" alt="">
                            <img src="<%= product.product_images.second.image.url(:original) if product.product_images.present? && product.product_images.second.present? %>" alt="">
                          </div>
                          <% end %>
                          <div class="product_content">
                            <div class="product_price">$<%= product.price %></div>
                            <div class="product_name">
                              <div>
                                <a href="<%= product_path(id: product.id) %>" tabindex="0"><%= product.name %></a>
                              </div>
                            </div>
                          </div>
                          <% if check_favorite(product.id) == true %>
                            <%= link_to remove_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                              <div class="product_fav active" id="<%= "in_product_#{product.id}"%>">
                                <i class="fas fa-heart"></i>
                              </div>
                            <% end %>
                          <% else %>
                            <%= link_to add_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                              <div class="product_fav" id="<%= "in_product_#{product.id}"%>">
                                <i class="fas fa-heart"></i>
                              </div>
                            <% end %>
                          <% end %>
                          <ul class="product_marks">
                            <li class="product_mark product_discount">-25%</li>
                            <li class="product_mark product_new">new</li>
                          </ul>
                        </div>
                      </div>
                    <% end %>
                  <% end %>

                </div>
                <div class="featured_slider_dots_cover"></div>
              </div>

              <!-- Product Panel -->
              <div class="product_panel panel">
                <div class="featured_slider slider">

                  <!-- Slider Item -->
                  <% if get_car_lights.present? %>
                    <% get_car_lights.each do |product| %>
                      <div class="featured_slider_item">
                        <div class="product_item is_new" id="product_<%= product.id %>">
                          <%= link_to product_detail_modal_path(id: product.id) , remote: true, :class=>"btn" do %>
                          <div class="product_image d-flex flex-column align-items-center justify-content-center">
                            <img src="<%= product.product_images.first.image.url(:original) if product.product_images.present? %>" alt="">
                            <img src="<%= product.product_images.second.image.url(:original) if product.product_images.present? && product.product_images.second.present? %>" alt="">
                          </div>
                          <% end %>
                          <div class="product_content">
                            <div class="product_price">$<%= product.price %></div>
                            <div class="product_name">
                              <div>
                                <a href="<%= product_path(id: product.id) %>" tabindex="0"><%= product.name %></a>
                              </div>
                            </div>
                          </div>
                          <% if check_favorite(product.id) == true %>
                            <%= link_to remove_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                              <div class="product_fav active" id="<%= "in_product_#{product.id}"%>">
                                <i class="fas fa-heart"></i>
                              </div>
                            <% end %>
                          <% else %>
                            <%= link_to add_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                              <div class="product_fav" id="<%= "in_product_#{product.id}"%>">
                                <i class="fas fa-heart"></i>
                              </div>
                            <% end %>
                          <% end %>
                          <ul class="product_marks">
                            <li class="product_mark product_discount">-25%</li>
                            <li class="product_mark product_new">new</li>
                          </ul>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
                <div class="featured_slider_dots_cover"></div>
              </div>

            </div>
          </div>

app/views/products/_trends.html.erb
<div class="trends col-7 ml-auto col-lg-12">
  <div class="trends_background" style="background-image:url(/assets/trends_background.jpg)"></div>
    <div class="trends_overlay"></div>
    <div class="container">
      <div class="row">
        <!-- Trends Content -->
        <div class="col-lg-3 col-7 ml-auto">
          <div class="trends_container">
            <h2 class="trends_title">Trends 2018</h2>
            <div class="trends_text"><p>Most trending products of 2018.</p></div>
            <div class="trends_slider_nav">
              <div class="trends_prev trends_nav"><i class="fas fa-angle-left ml-auto"></i></div>
              <div class="trends_next trends_nav"><i class="fas fa-angle-right ml-auto"></i></div>
            </div>
          </div>
        </div>
        <!-- Trends Slider -->
          <div class="col-lg-9">
            <div class="trends_slider_container">
            <!-- Trends Slider -->
              <div class="owl-carousel owl-theme trends_slider">
              <!-- Trends Slider Item -->
                <% if ProductType.find(1237).products.present? %>
                  <% ProductType.find(1237).products.includes(:product_type, :product_images).sample(10).each do |product| %>
                    <div class="owl-item">
                      <div class="trends_item is_new">
                        <%= link_to product_detail_modal_path(id: product.id) , remote: true, :class=>"btn" do %>
                          <div class="trends_image d-flex flex-column align-items-center justify-content-center">
                            <img src="<%= product.product_images.first.image.url(:original) if product.product_images.present? %>" alt="">
                          </div>
                        <% end %>
                    <div class="trends_content">
                      <div class="trends_category"><a href="#"><%= product.product_type.name %></a></div>
                      <div class="trends_info clearfix">
                        <div class="trends_name"><a href="<%= product_path(id: product.id) %>" tabindex="0"><%= product.name %></a></div>
                        <div class="trends_price">$<%= product.price %></div>
                      </div>
                    </div>
                    <ul class="trends_marks">
                      <li class="trends_mark trends_discount">-25%</li>
                      <li class="trends_mark trends_new">new</li>
                    </ul>
                    <% if check_favorite(product.id) == true %>
                      <%= link_to remove_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                        <div class="trends_fav active" id="<%= "in_product_#{product.id}"%>">
                          <i class="fas fa-heart"></i>
                        </div>
                      <% end %>
                    <% else %>
                      <%= link_to add_favorite_path(product_id: product.id), class: "fav_link", remote: true do %>
                        <div class="trends_fav" id="<%= "in_product_#{product.id}"%>">
                          <i class="fas fa-heart"></i>
                        </div>
                      <% end %>
                    <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>