config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    resources :brands, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :product_types, only: [:index, :new, :create]
    resources :users, only: [:index]
    resources :conversations, only: [:index, :new, :show]
    resources :personal_messages, only: [:new, :create]
    resources :orders, only: [] do
      collection do
        get :unpaid_orders
        get :paid_orders
        get :shipped_orders
      end
      member do
        get :ship_order
      end
    end
  end
  resources :shopping_carts, except: [:new, :create, :edit, :update, :destroy, :index, :show] do
    collection do
      get 'checkout'
      post 'process_payment'
      get 'remove_items_from_cart'
    end
  end
  resources :conversations
  resources :personal_messages

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", passwords: 'users/passwords' }
  root to: 'home#index'
  get 'home/shop' => "home#shop", as: :shop
  get 'home/sub_categories' => "home#sub_categories", as: :sub_categories
  get 'home/product_types' => "home#product_types", as: :product_types
  get 'home/product' => "home#product", as: :product
  get 'home/cart' => "home#cart", as: :cart
  get 'home/contact' => "home#contact", as: :contact
  get 'home/blog' => "home#blog", as: :blog
  get 'home/blog_show' => "home#blog_show", as: :blog_show
  get 'home/add_favorite' => "home#add_favorite", as: :add_favorite
  get 'home/remove_favorite' => "home#remove_favorite", as: :remove_favorite
  get 'home/my_favorites' => "home#my_favorites", as: :my_favorites
  get 'home/add_to_cart' => "home#add_to_cart", as: :add_to_cart
  post 'home/create_shipping' => "home#create_shipping", as: :create_shipping
  get 'home/product_detail_modal' => "home#product_detail_modal", as: :product_detail_modal
  get 'home/about_us' => "home#about_us", as: :about_us
  get 'home/contact_us' => "home#contact_us", as: :contact_us
  get 'home/terms_of_use' => "home#terms_of_use", as: :terms_of_use
  get 'home/discount_policy' => "home#discount_policy", as: :discount_policy
  get 'home/return' => "home#return", as: :return
  get 'home/privacy_policy' => "home#privacy_policy", as: :privacy_policy
  get 'home/shipping_help' => "home#shipping_help", as: :shipping_help
  get 'home/see_all' => 'home#see_all'
  resources :dashboards do
    collection do
      get :order_shipping_details
    end
  end

  get 'catergory_list' => "dashboards#catergory_list", as: :catergory_list
  get 'add_catergory' => "dashboards#add_catergory", as: :add_catergory
  post 'create_catergory' => "dashboards#create_catergory", as: :create_catergory
  get 'edit_category' => "dashboards#edit_category", as: :edit_category
  put 'update_category' => "dashboards#update_category", as: :update_category

  get 'sub_category_list' => "dashboards#sub_category_list", as: :sub_category_list
  get 'add_sub_category' => "dashboards#add_sub_category", as: :add_sub_category
  post 'create_sub_category' => "dashboards#create_sub_category", as: :create_sub_category

  get 'store' => "dashboards#store", as: :store
  get 'add_store' => "dashboards#add_store", as: :add_store
  post 'create_store' => "dashboards#create_store", as: :create_store

  get 'product_list' => "dashboards#product_list", as: :product_list
  get 'add_product' => "dashboards#add_product", as: :add_product
  post 'create_product' => "dashboards#create_product", as: :create_product
  get 'edit_product' => "dashboards#edit_product", as: :edit_product
  put 'update_product' => "dashboards#update_product", as: :update_product
  get 'delete_product' => "dashboards#delete_product", as: :delete_product

  get 'product_color_list' => "dashboards#product_color_list", as: :product_color_list
  get 'add_product_color' => "dashboards#add_product_color", as: :add_product_color
  post 'create_product_color' => "dashboards#create_product_color", as: :create_product_color

  get 'product_size_list' => "dashboards#product_size_list", as: :product_size_list
  get 'add_product_size' => "dashboards#add_product_size", as: :add_product_size
  post 'create_product_size' => "dashboards#create_product_size", as: :create_product_size

  get 'closure_type_list' => "dashboards#closure_type_list", as: :closure_type_list
  get 'add_closure_type' => "dashboards#add_closure_type", as: :add_closure_type
  post 'create_closure_type' => "dashboards#create_closure_type", as: :create_closure_type


  get 'collar_list' => "dashboards#collar_list", as: :collar_list
  get 'add_collar_type' => "dashboards#add_collar_type", as: :add_collar_type
  post 'create_collar_type' => "dashboards#create_collar_type", as: :create_collar_type

  get 'craft_list' => "dashboards#craft_list", as: :craft_list
  get 'add_craft_type' => "dashboards#add_craft_type", as: :add_craft_type
  post 'create_craft_type' => "dashboards#create_craft_type", as: :create_craft_type


  get 'design_list' => "dashboards#design_list", as: :design_list
  get 'add_design' => "dashboards#add_design", as: :add_design
  post 'create_design' => "dashboards#create_design", as: :create_design

  get 'design_type_list' => "dashboards#design_type_list", as: :design_type_list
  get 'add_design_type' => "dashboards#add_design_type", as: :add_design_type
  post 'create_design_type' => "dashboards#create_design_type", as: :create_design_type

  get 'pattern_style_list' => "dashboards#pattern_style_list", as: :pattern_style_list
  get 'add_pattern_style' => "dashboards#add_pattern_style", as: :add_pattern_style
  post 'create_pattern_style' => "dashboards#create_pattern_style", as: :create_pattern_style


  get 'sleeve_type_list' => "dashboards#sleeve_type_list", as: :sleeve_type_list
  get 'add_sleeve_type' => "dashboards#add_sleeve_type", as: :add_sleeve_type
  post 'create_sleeve_type' => "dashboards#create_sleeve_type", as: :create_sleeve_type


  get 'styles_list' => "dashboards#styles_list", as: :styles_list
  get 'add_style' => "dashboards#add_style", as: :add_style
  post 'create_style' => "dashboards#create_style", as: :create_style

  get 'shipping_prices' => "dashboards#shipping_prices", as: :shipping_prices
  get 'add_shipping_prices' => "dashboards#add_shipping_prices", as: :add_shipping_prices
  post 'create_shipping_price' => "dashboards#create_shipping_price", as: :create_shipping_price

  get 'orders_list' => "dashboards#orders_list", as: :orders_list
  get 'pending_orders' => "dashboards#pending_orders", as: :pending_orders
  get 'completed_orders' => "dashboards#completed_orders", as: :completed_orders
  get 'order_details' => "dashboards#order_details", as: :order_details
  get 'my_order_details' => "dashboards#my_order_details", as: :my_order_details
  get 'change_product_status' => "dashboards#change_product_status", as: :change_product_status
  get 'change_order_status' => "dashboards#change_order_status", as: :change_order_status
  mount ActionCable.server => '/cable'

  #For static pages
  get "/pages/:page" => "pages#show"
  resources :states, only: :index
end

app/views/layouts/partials/_copyright_web.html.erb
<%= link_to new_personal_message_path(receiver_id: User.admin) do %>
  <div class="contact-us d-none d-sm-block">
    <i class="fa fa-comments" aria-hidden="true"></i>Live support agent</span>
  </div>
<% end %>

<div class="copyright">
  <div class="container">
    <div class="row">
      <div class="col">

        <div class="copyright_container flex-sm-row flex-column align-items-center justify-content-start">
          <div class="copyright_content">
            <%# Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="#" target="_blank">Usama Ashraf</a> %>
            <div class="row">
              <div class="col-lg-9 col-md-8">
                  <div class="mini-footer__links">
                    <nav role="navigation" class="mini-footer__nav">
                      <ul>
                        <li>
                          <a href="<%= about_us_path %>" data-lid="ft_cou">About us</a>
                        </li>
                        <li>
                          <a href="<%= contact_us_path %>" data-lid="ft_pp">Contact us</a>
                        </li>
                        <li>
                          <a href="<%= terms_of_use_path %>" data-lid="ft_ip">Terms of use</a>
                        </li>
                        <li>
                          <a href="<%= about_us_path %>" data-lid="ft_cou">Sitemap</a>
                        </li>
                        <li>
                          <a href="<%= discount_policy_path %>" data-lid="ft_ip">Discount Policy</a>
                        </li>
                        <li>
                          <a href="<%= return_path %>" data-lid="ft_cou">Return Policy</a>
                        </li>
                        <li>
                          <a href="<%= privacy_policy_path %>" data-lid="ft_pp">Privacy notice</a>
                        </li>
                        <li>
                          <a href="<%= shipping_help_path %>" data-lid="ft_ip">How long to receive your order?</a>
                        </li>
                      </ul>
                    </nav>
                  </div>
              </div>
              <div class="col-lg-3 col-md-4">
                <div class="logos ml-sm-auto">
                  <ul class="logos_list">
                    <li><a href="#"><img src="/assets/logos_1.png" alt=""></a></li>
                    <li><a href="#"><img src="/assets/logos_2.png" alt=""></a></li>
                    <li><a href="#"><img src="/assets/logos_3.png" alt=""></a></li>
                    <li><a href="#"><img src="/assets/logos_4.png" alt=""></a></li>
                  </ul>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/partials/_dashboard_sidenav.html.erb
<% if current_user.email == "admin@gmail.com" %>
    <!-- MENU SIDEBAR-->
    <aside class="menu-sidebar d-none d-lg-block">
      <div class="logo">
        <a href="<%= root_path %>">
          <img src="/assets/Talotsing source-02.png" alt="Talotsing" />
        </a>
      </div>
      <div class="menu-sidebar__content js-scrollbar1">
        <nav class="navbar-sidebar">
          <ul class="list-unstyled navbar__list">
            <li class="active has-sub">
              <%= link_to dashboards_path do  %>
                  <i class="fas fa-tachometer-alt"></i>Dashboard
              <% end %>
              <%= link_to dashboard_users_path do  %>
                <i class="fas fa-tachometer-alt"></i>Users
              <% end %>
              <%= link_to unpaid_orders_dashboard_orders_path do  %>
                <i class="fas fa-tachometer-alt"></i>Unpaid Orders
              <% end %>
              <%= link_to paid_orders_dashboard_orders_path do  %>
                <i class="fas fa-tachometer-alt"></i>To Be Shipped Orders
              <% end %>
              <%= link_to  shipped_orders_dashboard_orders_path do  %>
                <i class="fas fa-tachometer-alt"></i>Shipped
              <% end %>
              <!--<ul class="list-unstyled navbar__sub-list js-sub-list">-->
                <!--<li>-->
                  <!--<a href="index.html">Dashboard 1</a>-->
                <!--</li>-->
                <!--<li>-->
                  <!--<a href="index2.html">Dashboard 2</a>-->
                <!--</li>-->
                <!--<li>-->
                  <!--<a href="index3.html">Dashboard 3</a>-->
                <!--</li>-->
                <!--<li>-->
                  <!--<a href="index4.html">Dashboard 4</a>-->
                <!--</li>-->
              <!--</ul>-->
            </li>
            <li>
              <%= link_to dashboard_brands_path do  %>
                  <i class="fas fa-chart-bar"></i>Brands
              <% end %>
            </li>
            <li>
              <%= link_to catergory_list_path do  %>
                  <i class="fas fa-chart-bar"></i>Product Categories
              <% end %>
            </li>
            <li>
              <%= link_to sub_category_list_path do  %>
                  <i class="fas fa-chart-bar"></i>Product sub categories
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_product_types_path do %>
                <i class="fas fa-chart-bar"></i>Product types
              <% end %>
            </li>
            <li>
              <%= link_to store_path do  %>
                  <i class="fas fa-chart-bar"></i>Your Store
              <% end %>
            </li>
            <li>
              <%= link_to product_list_path do  %>
                  <i class="fas fa-chart-bar"></i>Products list
              <% end %>
            </li>
            <li>
              <%= link_to product_color_list_path do  %>
                <i class="fas fa-chart-bar"></i>Product Colors list
              <% end %>
            </li>

            <li>
              <%= link_to product_size_list_path do  %>
                <i class="fas fa-chart-bar"></i>Product Sizes list
              <% end %>
            </li>
            <li>
              <%= link_to closure_type_list_path do  %>
                <i class="fas fa-chart-bar"></i>Closure Type list
              <% end %>
            </li>
            <li>
              <%= link_to collar_list_path do  %>
                <i class="fas fa-chart-bar"></i>Collar list
              <% end %>
            </li>
            <li>
              <%= link_to craft_list_path do  %>
                <i class="fas fa-chart-bar"></i>Craft list
              <% end %>
            </li>
            <li>
              <%= link_to design_list_path do  %>
                <i class="fas fa-chart-bar"></i>Design list
              <% end %>
            </li>
            <li>
              <%= link_to design_type_list_path do  %>
                <i class="fas fa-chart-bar"></i>Design Type list
              <% end %>
            </li>
            <li>
            <%= link_to pattern_style_list_path do  %>
              <i class="fas fa-chart-bar"></i>Pattern Style list
            <% end %>
          </li>
            <li>
            <%= link_to sleeve_type_list_path do  %>
              <i class="fas fa-chart-bar"></i>Sleeve Type list
            <% end %>
          </li>
            <li>
              <%= link_to styles_list_path do  %>
                <i class="fas fa-chart-bar"></i>Style list
              <% end %>
            </li>



            <li>
              <%= link_to shipping_prices_path do  %>
                <i class="fas fa-chart-bar"></i>Shipping Prices list
              <% end %>
            </li>
          </ul>
        </nav>
      </div>
    </aside>
    <!-- END MENU SIDEBAR-->

<% elsif current_user.customer? %>
    <!-- MENU SIDEBAR-->
    <aside class="menu-sidebar d-none d-lg-block">
      <div class="logo">
        <a href="<%= root_path %>">
          <img src="/assets/Talotsing source-02.png" alt="Talotsing" />
        </a>
      </div>
      <div class="menu-sidebar__content js-scrollbar1">
        <nav class="navbar-sidebar">
          <ul class="list-unstyled navbar__list">
            <li>
              <%= link_to orders_list_path do  %>
                <i class="fas fa-chart-bar"></i>My Orders
              <% end %>
            </li>
          </ul>
        </nav>
      </div>
    </aside>
    <!-- END MENU SIDEBAR-->

<% elsif current_user.vendor? %>
    <!-- MENU SIDEBAR-->
    <aside class="menu-sidebar d-none d-lg-block">
      <div class="logo">
        <a href="<%= root_path %>">
          <img src="/assets/Talotsing source-02.png" alt="Talotsing" />
        </a>
      </div>
      <div class="menu-sidebar__content js-scrollbar1">
        <nav class="navbar-sidebar">
          <ul class="list-unstyled navbar__list">
            <li class="active has-sub">
              <a class="js-arrow" href="#">
                <i class="fas fa-tachometer-alt"></i>Dashboard</a>
              <ul class="list-unstyled navbar__sub-list js-sub-list">
                <li>
                  <a href="index.html">Dashboard 1</a>
                </li>
                <li>
                  <a href="index2.html">Dashboard 2</a>
                </li>
                <li>
                  <a href="index3.html">Dashboard 3</a>
                </li>
                <li>
                  <a href="index4.html">Dashboard 4</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="chart.html">
                <i class="fas fa-chart-bar"></i>Charts</a>
            </li>
            <li>
              <a href="table.html">
                <i class="fas fa-table"></i>Tables</a>
            </li>
            <li>
              <a href="form.html">
                <i class="far fa-check-square"></i>Forms</a>
            </li>
            <li>
              <a href="#">
                <i class="fas fa-calendar-alt"></i>Calendar</a>
            </li>
            <li>
              <a href="map.html">
                <i class="fas fa-map-marker-alt"></i>Maps</a>
            </li>
            <li class="has-sub">
              <a class="js-arrow" href="#">
                <i class="fas fa-copy"></i>Pages</a>
              <ul class="list-unstyled navbar__sub-list js-sub-list">
                <li>
                  <a href="login.html">Login</a>
                </li>
                <li>
                  <a href="register.html">Register</a>
                </li>
                <li>
                  <a href="forget-pass.html">Forget Password</a>
                </li>
              </ul>
            </li>
            <li class="has-sub">
              <a class="js-arrow" href="#">
                <i class="fas fa-desktop"></i>UI Elements</a>
              <ul class="list-unstyled navbar__sub-list js-sub-list">
                <li>
                  <a href="button.html">Button</a>
                </li>
                <li>
                  <a href="badge.html">Badges</a>
                </li>
                <li>
                  <a href="tab.html">Tabs</a>
                </li>
                <li>
                  <a href="card.html">Cards</a>
                </li>
                <li>
                  <a href="alert.html">Alerts</a>
                </li>
                <li>
                  <a href="progress-bar.html">Progress Bars</a>
                </li>
                <li>
                  <a href="modal.html">Modals</a>
                </li>
                <li>
                  <a href="switch.html">Switchs</a>
                </li>
                <li>
                  <a href="grid.html">Grids</a>
                </li>
                <li>
                  <a href="fontawesome.html">Fontawesome Icon</a>
                </li>
                <li>
                  <a href="typo.html">Typography</a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </aside>
    <!-- END MENU SIDEBAR-->

<% end %>

app/views/layouts/partials/_footer_web.html.erb
<footer class="footer" style="background-color: #232f3e;">
  <div class="container">
    <div class="row">

      <div class="col-lg-3 footer_col">
        <div class="footer_column footer_contact">
          <div class="logo_container">
            <div class="logo"><img src="/assets/logoo 3.png" style="width: 189px;margin-left: -7px;"></div>
          </div>
          <div class="footer_title">Got Question? Call Us 24/7</div>
          <div class="footer_phone">+16266150262</div>
          <div class="footer_contact_text">
            <p>1407 Fulton St, Brooklyn</p>
            <p>Brooklyn, NY 11216</p>
          </div>
          <div class="footer_social">
            <ul>
              <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
              <li><a href="#"><i class="fab fa-twitter"></i></a></li>
              <li><a href="#"><i class="fab fa-youtube"></i></a></li>
              <li><a href="#"><i class="fab fa-google"></i></a></li>
              <li><a href="#"><i class="fab fa-vimeo-v"></i></a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-lg-2 offset-lg-2">
        <div class="footer_column">
          <div class="footer_title">Find it Fast</div>
          <ul class="footer_list">
            <% @count = Category.all.size/2 %>
            <% Category.first(@count).each do |category| %>
                <li><a href="<%= shop_path(category: category.id)%>"><%= category.name %></a></li>
            <% end %>
            <!--<li><a href="#">Computers & Laptops</a></li>-->
            <!--<li><a href="#">Cameras & Photos</a></li>-->
            <!--<li><a href="#">Hardware</a></li>-->
            <!--<li><a href="#">Smartphones & Tablets</a></li>-->
            <!--<li><a href="#">TV & Audio</a></li>-->
          </ul>
          <!--<div class="footer_subtitle">Gadgets</div>-->
          <!--<ul class="footer_list">-->
            <!--<li><a href="#">Gadgets</a></li>-->
            <!--<li><a href="#">Car Electronics</a></li>-->
          <!--</ul>-->
        </div>
      </div>

      <div class="col-lg-2">
        <div class="footer_column">
          <ul class="footer_list footer_list_2">
            <% Category.last(@count).each do |category| %>
                <li><a href="<%= shop_path(category: category.id)%>"><%= category.name %></a></li>
            <% end %>
            <!--<li><a href="#">Video Games & Consoles</a></li>-->
            <!--<li><a href="#">Accessories</a></li>-->
            <!--<li><a href="#">Cameras & Photos</a></li>-->
            <!--<li><a href="#">Hardware</a></li>-->
            <!--<li><a href="#">Computers & Laptops</a></li>-->
          </ul>
        </div>
      </div>

      <div class="col-lg-2">
        <div class="footer_column">
          <div class="footer_title">Customer Care</div>
          <ul class="footer_list">
            <li><a href="<%= dashboards_path%>">My Account</a></li>
            <li><a href="<%= my_favorites_path %>">My Favorites</a></li>
            <li><a href="<%= about_us_path %>">About us</a></li>
            <li><a href="<%= contact_us_path %>">Contact us</a></li>
            <li><a href="<%= terms_of_use_path %>">Terms of use</a></li>
            <li><a href="<%= return_path %>">Return Policy</a></li>
            <li><a href="<%= privacy_policy_path %>">Privacy notice</a></li>
          </ul>
        </div>
      </div>

    </div>
  </div>
</footer>

<style>
  .footer_list li a {
    color: #999;
  }
  .footer_title {
    color: #ddd;
  }
    .footer_phone{
      color: #ddd;
    }
    .footer_contact_text p{
      color: #ddd;
    }
</style>

app/views/layouts/partials/_search_bar.html.erb
<div class="header_main" style="background-color: #232f3e;">
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-sm-3 col-3 order-1">
        <div class="logo_container">
          <div class="logo"><a href="<%= root_path %>"><img src="/assets/logoo 3.png"></a></div>
        </div>
      </div>
            <!-- Search -->
      <div class="col-lg-6 col-12 order-lg-2 order-3 text-lg-left text-right">
        <div class="header_search d-block" >
          <div class="header_search_content">
            <div class="header_search_form_container">
              <%= form_for :search_product, url: shop_path, class: "header_search_form clearfix", method: :get do |f| %>
                <%= f.text_field :keyword, class: "header_search_input", required: false,
                 placeholder: "Search for products..." %>
                <%= f.hidden_field :category, id: "search_category" %>
                <div class="custom_dropdown" style="background-color: white;">
                  <div class="custom_dropdown_list">
                    <span class="custom_dropdown_placeholder clc">All Categories</span>
                    <i class="fas fa-chevron-down"></i>
                    <ul class="custom_list clc" id="category_search_params">
                      <% Category.where(see_all:false).each do |category| %>
                        <li> <%= link_to category.name, sub_categories_path(category: category.id) %> </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
                <button type="submit" class="header_search_button trans_300" value="Submit"
                 style="background-color: #febd69;"><img src="/assets/search.png" alt=""></button>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row float-right d-lg-none mt-2">
          <%= link_to "Live Support", new_personal_message_path(receiver_id: User.admin)%>
        </div>
      </div>
            <!-- Wishlist -->
      <div class="col-lg-4 col-9 order-lg-3 order-2 text-lg-left text-right">
        <div class="wishlist_cart d-flex flex-row align-items-center justify-content-end">
          <div class="wishlist d-flex flex-row align-items-center justify-content-end">
            <a href="<%= my_favorites_path %>"><div class="wishlist_icon"><img src="/assets/heart.png" alt=""></div></a>
            <div class="wishlist_content">
              <div class="wishlist_text">
                <a href="<%= my_favorites_path %>" style="color: #ffffff;">My Favorites</a>
              </div>
              <% if !session[:favorites].nil? %>
                <div class="wishlist_count" style="color: #ffffff;">
                  <%= session[:favorites].count if !session[:favorites].nil? %>
                </div>
              <% elsif current_user.present? %>
                <div class="wishlist_count" style="color: #ffffff;">
                  <%= current_user.user_favorites.count if current_user.user_favorites.present? %>
                </div>
              <% end %>
            </div>
          </div>

          <!-- Cart -->
          <a href="<%= checkout_shopping_carts_path %>">
            <div class="cart">
              <div class="cart_container d-flex flex-row align-items-center justify-content-end">
                <div class="cart_icon">
                  <img src="/assets/cart.png" alt="">
                  <% if !session[:shop_cart].nil? %>
                    <div class="cart_count" style="background-color: #febd69; "><span style="color: black;"><%= session[:shop_cart].count if !session[:shop_cart].nil? %></span></div>
                  <% elsif current_user.present? %>
                    <div class="cart_count" style="background-color: #febd69; "><span style="color: black;"><%= current_user.orders.where(status: "pending").last.order_items.size if current_user.orders.where(status: "pending").present? %></span></div>
                  <% end %>
                </div>
                <div class="cart_content">
                  <% if current_user.present? && current_user.orders.where(status: "pending").present? %>
                    <div class="cart_text"><a href="<%= checkout_shopping_carts_path %>" style="    color: #ffffff;">Cart</a></div>
                    <div class="cart_price" style="color: #ffffff;"><%= number_to_currency(cart_total) %></div>
                  <% elsif !session[:shop_cart].nil? %>
                    <div class="cart_text"><a  href="<%= checkout_shopping_carts_path %>" style=" color: #ffffff;">Cart</a></div>
                    <div class="cart_price" style="color: #ffffff;"><%= number_to_currency(cart_total) if !session[:shop_cart].nil? %></div>
                  <% else %>
                    <div class="cart_text"><a  style="    color: #ffffff;">Cart</a></div>
                    <div class="cart_price" style="color: #ffffff;">$0</div>
                  <% end %>
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<style>
  .header_search_input{
    height: 50px;
  }
  #break_line{
    display: block;
    color: black;
    margin-top: 0.5em;
    border-top: 1px solid #090909;
    margin-bottom: 0.5em;
    margin-left: auto;
    margin-right: auto;
    border-style: inset;
    border-width: 1px;
  }
  .main_nav_dropdown li a {
    color: #000000;
  }
  @media only screen and (max-width: 767px){
    .main_nav_content{
      background-color: #232f3e;
    }
    .custom_dropdown_placeholder {
      font-size: 12px;
    }
    .custom_list li {
      font-size: 8px
    }
  }
</style>
<script>
    $(document).on("click", "#category_search_params li a", function() {
        $("#search_category").val($(this).data("value"));
        console.log($("#search_category").val());
    });
    var acc = document.getElementsByClassName("mbl_cls_li");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var mbl_panel = $(this).next('ul.page_menu_selection');
            if(mbl_panel.hasClass('active'))
              {
                  mbl_panel.toggleClass('active');
                  TweenMax.to(mbl_panel, 0.3, {height:0});
              }
              else
              {
                  mbl_panel.toggleClass('active');
                  TweenMax.set(mbl_panel, {height:"auto"});
                  TweenMax.from(mbl_panel, 0.3, {height:0});
              }
        });
    }
    function click_menu() {
        $(".menu_trigger").click();
    }
    $("#mobile_search").keypress(function(event) {
        if (event.which == 13) {
            event.preventDefault();
            $("#mobile_form").submit();
        }
    });
</script>

app/views/layouts/partials/_user_dashboard_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-custom">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">My Orders <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Message Center</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Wish List</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Account Settings</a>
    </li>
  </ul>
</nav>
<style>
  .navbar-custom {
    background-color: #febd69;
  }
</style>